openapi: 3.2.0
info:
  contact:
    email: support@posit.co
    name: Posit Connect Support
    url: https://support.posit.co/hc/en-us
  description: '## Overview


    The Posit Connect Server API can be used to perform certain

    user actions remotely.'
  license:
    name: Commercial. Copyright 2015-2026 Posit Software, PBC. All Rights Reserved.
    url: https://posit.co/about/eula/
  termsOfService: https://posit.co/about/eula/
  title: Posit Connect API Reference System Checks API
  version: 1.0.1
servers:
- url: /__api__
security:
- apiKey: []
tags:
- name: System Checks
paths:
  /v1/system/checks:
    get:
      description: 'List all system check runs that have been requested.

        You must have administrator privileges to perform this action.'
      operationId: listSystemCheckRuns
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SystemCheckRun'
                type: array
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation is invalid.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested object does not exist.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: List system check runs
      tags:
      - System Checks
    post:
      description: 'Start a system check run. The tests run in the background, and you can

        poll for status using the returned run ID.

        You must have administrator privileges to perform this action.'
      operationId: runSystemChecks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRunInput'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemCheckRun'
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation is invalid.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested object does not exist.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: Start a system check run
      tags:
      - System Checks
  /v1/system/checks/{id}:
    delete:
      description: Delete a system check run and the associated results.
      operationId: deleteSystemCheckRun
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation is invalid.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested object does not exist.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: Delete a system check run
      tags:
      - System Checks
    get:
      description: Get the status of a system check run.
      operationId: getSystemCheckRun
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemCheckRun'
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation is invalid.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested object does not exist.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: Get the status of a system check run
      tags:
      - System Checks
  /v1/system/checks/{id}/results:
    get:
      description: Get the results of a system check run.
      operationId: getSystemCheckRunResults
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemCheckRunResults'
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation is invalid.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested object does not exist.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: Get the results of a system check run
      tags:
      - System Checks
components:
  schemas:
    APIError:
      additionalProperties: false
      description: The error object returned by the API on failure.
      properties:
        code:
          description: The specific code for the type of error returned. See the [API error codes reference](#api-error-codes) for the full set of values.
          type: integer
        error:
          description: A description of the problem that was encountered.
          type: string
        payload:
          description: Additional error details, if any. The structure varies by error type.
          type:
          - object
          - 'null'
      required:
      - code
      - error
      type: object
    SystemCheckRun:
      additionalProperties: false
      description: The fields returned when listing system check runs or getting the status of a run.
      properties:
        id:
          description: The unique identifier for this test run.
          example: '2'
          type: string
        start_time:
          description: The timestamp (RFC3339) of when this run was started.
          example: '2006-01-02T15:04:05-07:00'
          format: date-time
          type: string
        hostname:
          description: The hostname where this test was run.
          example: connect.example.com
          type: string
        status:
          description: 'The status of this test run, one of: requested, running, done, canceled.'
          enum:
          - requested
          - running
          - done
          - canceled
          example: done
          type: string
        passed:
          description: The number of tests in this run that have passed.
          example: 29
          format: int32
          type: integer
        failed:
          description: The number of tests in this run that have failed.
          example: 1
          format: int32
          type: integer
      type: object
    SystemCheckRunResults:
      additionalProperties: false
      description: Fields containing results of a specific system check run.
      properties:
        run:
          allOf:
          - $ref: '#/components/schemas/SystemCheckRun'
          description: The run that was requested.
        results:
          description: The results of the system check run.
          items:
            $ref: '#/components/schemas/SystemCheckRunResult'
          type: array
      type: object
    TestInfo:
      additionalProperties: false
      description: Fields describing a specific test or test group.
      properties:
        name:
          description: The name of this test.
          example: environment
          type: string
        args:
          description: The arguments that will be passed to this test.
          type: string
      type: object
    CreateRunInput:
      additionalProperties: false
      description: The fields to provide when running system checks.
      properties:
        hostname:
          description: The hostname where this test was run. Optional. Defaults to the host
          example: connect.example.com
          type:
          - string
          - 'null'
      type: object
    SystemCheckRunResult:
      additionalProperties: false
      description: The fields describing a single system check result.
      properties:
        group:
          allOf:
          - $ref: '#/components/schemas/TestInfo'
          description: Information about the test group that was run.
        test:
          allOf:
          - $ref: '#/components/schemas/TestInfo'
          description: Information about the test that was run.
        passed:
          description: Boolean indicating whether the test passed.
          example: true
          type: boolean
        output:
          description: The textual output produced while running the test.
          type: string
        error:
          description: The error that occurred while running this test, or empty string if no error occurred.
          type: string
      type: object
  securitySchemes:
    apiKey:
      description: 'Prefix your API key with `Key `, e.g. `Key ABC123`.

        '
      in: header
      name: Authorization
      type: apiKey
