openapi: 3.2.0
info:
  contact:
    email: support@posit.co
    name: Posit Connect Support
    url: https://support.posit.co/hc/en-us
  description: '## Overview


    The Posit Connect Server API can be used to perform certain

    user actions remotely.'
  license:
    name: Commercial. Copyright 2015-2026 Posit Software, PBC. All Rights Reserved.
    url: https://posit.co/about/eula/
  termsOfService: https://posit.co/about/eula/
  title: Posit Connect API Reference Custom Documentation API
  version: 1.0.1
servers:
- url: /__api__
security:
- apiKey: []
tags:
- name: Custom Documentation
paths:
  /v1/system/documentation:
    delete:
      description: 'Delete the custom documentation for your Posit Connect server.

        This action is only available to administrators.

        Returns a 204 No Content response if the documentation was successfully deleted.

        Returns a 404 Not Found error if no custom documentation is configured.'
      operationId: deleteCustomDocumentation
      responses:
        '204':
          description: Successful response.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: You do not have permission to perform this operation.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested object does not exist.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: Delete custom documentation
      tags:
      - Custom Documentation
    get:
      description: 'Retrieve the custom documentation for your Posit Connect server, formatted using Markdown.

        Returns a 404 Not Found error if no custom documentation is configured.'
      operationId: getCustomDocumentation
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomDocumentationResult'
          description: Successful response.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested object does not exist.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: Get custom documentation
      tags:
      - Custom Documentation
    post:
      description: 'Set the custom documentation for your Posit Connect server, formatted using Markdown.

        The maximum length for the provided documentation is 500000 characters.

        This action is only available to administrators.

        Returns a 204 No Content response if the documentation was successfully set.'
      operationId: setCustomDocumentation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomDocumentationInput'
        required: true
      responses:
        '204':
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation is invalid.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: You do not have permission to perform this operation.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: Set custom documentation
      tags:
      - Custom Documentation
components:
  schemas:
    CustomDocumentationResult:
      additionalProperties: false
      description: The custom documentation for the Posit Connect server.
      properties:
        content:
          description: The custom documentation content, formatted using Markdown.
          type: string
        created_time:
          description: The time when the custom documentation was created.
          format: date-time
          type: string
      type: object
    APIError:
      additionalProperties: false
      description: The error object returned by the API on failure.
      properties:
        code:
          description: The specific code for the type of error returned. See the [API error codes reference](#api-error-codes) for the full set of values.
          type: integer
        error:
          description: A description of the problem that was encountered.
          type: string
        payload:
          description: Additional error details, if any. The structure varies by error type.
          type:
          - object
          - 'null'
      required:
      - code
      - error
      type: object
    CustomDocumentationInput:
      additionalProperties: false
      description: The custom documentation for the Posit Connect server.
      properties:
        content:
          description: The custom documentation content, formatted using Markdown.
          type: string
        created_time:
          description: The time when the custom documentation was created.
          format: date-time
          type: string
      type: object
  securitySchemes:
    apiKey:
      description: 'Prefix your API key with `Key `, e.g. `Key ABC123`.

        '
      in: header
      name: Authorization
      type: apiKey
