openapi: 3.2.0
info:
  contact:
    email: support@posit.co
    name: Posit Connect Support
    url: https://support.posit.co/hc/en-us
  description: '## Overview


    The Posit Connect Server API can be used to perform certain

    user actions remotely.'
  license:
    name: Commercial. Copyright 2015-2026 Posit Software, PBC. All Rights Reserved.
    url: https://posit.co/about/eula/
  termsOfService: https://posit.co/about/eula/
  title: Posit Connect API Reference System Information API
  version: 1.0.1
servers:
- url: /__api__
security:
- apiKey: []
tags:
- name: System Information
paths:
  /v1/system/caches/runtime:
    delete:
      description: 'Delete a content runtime package cache by specifying language, version,

        and execution environment.

        This action is only available to administrators.'
      operationId: deleteRuntimeCache
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteRuntimeCacheInput'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteRuntimeCacheResponse'
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation is invalid.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested object does not exist.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: Delete a runtime cache
      tags:
      - System Information
    get:
      description: 'List all content runtime caches. These include packrat and Python

        environment caches.

        This information is available only to administrators.'
      operationId: listRuntimeCaches
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RuntimeCaches'
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation is invalid.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: List runtime caches
      tags:
      - System Information
  /v1/system/hosts:
    get:
      description: 'List registered hosts.

        The default response includes hosts that are no longer active. Use the

        `active` parameter to return only active hosts. A host is considered

        active if it has checked in in the last 60 seconds.

        You must have administrator privileges to perform this action.'
      operationId: listHosts
      parameters:
      - description: false "Return only active hosts"
        in: query
        name: active
        schema:
          type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Host'
                type: array
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation is invalid.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested object does not exist.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: List Connect hosts
      tags:
      - System Information
  /v1/system/offhost/service-accounts:
    get:
      description: 'Applicable to Connect instances configured for off-host execution.

        List the Kubernetes service accounts discovered when Connect started.

        This action is available to publishers and administrators.'
      operationId: listServiceAccounts
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceAccounts'
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation is invalid.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: List Kubernetes service accounts
      tags:
      - System Information
components:
  schemas:
    RuntimeCaches:
      additionalProperties: false
      description: An object containing an array of runtime caches.
      properties:
        caches:
          description: The list of runtime caches.
          items:
            $ref: '#/components/schemas/RuntimeCache'
          type: array
      type: object
    APIError:
      additionalProperties: false
      description: The error object returned by the API on failure.
      properties:
        code:
          description: The specific code for the type of error returned. See the [API error codes reference](#api-error-codes) for the full set of values.
          type: integer
        error:
          description: A description of the problem that was encountered.
          type: string
        payload:
          description: Additional error details, if any. The structure varies by error type.
          type:
          - object
          - 'null'
      required:
      - code
      - error
      type: object
    DeleteRuntimeCacheInput:
      additionalProperties: false
      description: Fields that describe the runtime cache to delete.
      properties:
        language:
          description: The language of the target cache; either "R" or "Python".
          example: R
          type: string
        version:
          description: The version of the target cache.
          example: 4.1.2
          type: string
        image_name:
          description: 'The execution environment of the target cache; either "Local" or an

            image name or identifier.'
          example: Local
          type: string
        dry_run:
          description: When true, check input but do not delete cache.
          example: true
          type: boolean
      type: object
    Host:
      additionalProperties: false
      description: The fields returned when listing Connect hosts.
      properties:
        hostname:
          description: The hostname or node name configured for the host.
          example: connect.example.com
          type: string
        version:
          description: The version of Connect running on the host.
          example: 2021.10.0
          type: string
        last_seen:
          description: The timestamp (RFC3339) of when this host last checked in.
          example: '2006-01-02T15:04:05-07:00'
          format: date-time
          type: string
      type: object
    ServiceAccounts:
      additionalProperties: false
      description: Kubernetes service accounts discovered when Connect started.
      properties:
        enabled:
          description: 'Whether or not Kubernetes service accounts can be specified individually by

            content item.

            Reflects the configuration set for

            [`Launcher.KubernetesContentServiceAccountSelection`](../admin/appendix/configuration/index.md#Launcher.KubernetesContentServiceAccountSelection).'
          type: boolean
        default:
          description: 'The default configured service account to execute content.

            Unless otherwise configured via [`Launcher.KubernetesDefaultServiceAccount`](../admin/appendix/configuration/index.md#Launcher.KubernetesDefaultServiceAccount)

            in your Connect configuration,

            this is the Kubernetes namespace default service account, "default."'
          type:
          - string
          - 'null'
        accounts:
          description: Array of strings with the service account names.
          items:
            type: string
          type: array
      type: object
    RuntimeCache:
      additionalProperties: false
      description: A cache of installed packages for a given language, version, and execution environment.
      properties:
        language:
          description: The runtime language of the cache.
          example: Python
          type: string
        version:
          description: The language version of the cache.
          example: 3.8.12
          type: string
        image_name:
          description: The name of the cache's execution environment.
          example: Local
          type: string
      type: object
    DeleteRuntimeCacheResponse:
      additionalProperties: false
      description: The response from a cache deletion request.
      properties:
        language:
          description: The runtime language of the target cache.
          example: Python
          type: string
        version:
          description: The language version of the target cache.
          example: 3.8.12
          type: string
        image_name:
          description: The name of the target cache's execution environment.
          example: Local
          type: string
        task_id:
          description: 'The identifier for the created deployment task.

            Always `null` for dry-run requests.'
          example: M49MsuXt6XVzlRdL
          type:
          - string
          - 'null'
      type: object
  securitySchemes:
    apiKey:
      description: 'Prefix your API key with `Key `, e.g. `Key ABC123`.

        '
      in: header
      name: Authorization
      type: apiKey
