openapi: 3.2.0
info:
  contact:
    email: support@posit.co
    name: Posit Connect Support
    url: https://support.posit.co/hc/en-us
  description: '## Overview


    The Posit Connect Server API can be used to perform certain

    user actions remotely.'
  license:
    name: Commercial. Copyright 2015-2026 Posit Software, PBC. All Rights Reserved.
    url: https://posit.co/about/eula/
  termsOfService: https://posit.co/about/eula/
  title: Posit Connect API Reference OAuth Sessions API
  version: 1.0.1
servers:
- url: /__api__
security:
- apiKey: []
tags:
- name: OAuth Sessions
paths:
  /v1/oauth/sessions:
    get:
      description: 'List OAuth sessions available to Posit Connect associated with the current user.

        If you have administrator privileges you can request all available sessions.'
      operationId: listOAuthSessions
      parameters:
      - description: false "When making a request with administrator privileges, include OAuth sessions for all users when set to true"
        in: query
        name: all
        schema:
          type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/OAuthSession'
                type: array
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation is invalid.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: You do not have permission to perform this operation.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested object does not exist.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: List OAuth sessions
      tags:
      - OAuth Sessions
  /v1/oauth/sessions/{guid}:
    delete:
      description: 'Delete the OAuth session associated with the provided guid.

        A user can delete their own sessions. Deleting sessions for other users requires administrator privileges.'
      operationId: deleteOAuthSession
      parameters:
      - in: path
        name: guid
        required: true
        schema:
          format: uuid
          type: string
      responses:
        '204':
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation is invalid.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: You do not have permission to perform this operation.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested object does not exist.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: Delete an OAuth session
      tags:
      - OAuth Sessions
    get:
      description: 'Get information about a specific OAuth session.

        If you have administrator privileges you can request details for any available session.'
      operationId: getOAuthSession
      parameters:
      - in: path
        name: guid
        required: true
        schema:
          format: uuid
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthSession'
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation is invalid.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested operation requires authentication.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: You do not have permission to perform this operation.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: The requested object does not exist.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: A server error occurred.
      summary: Get OAuth session details
      tags:
      - OAuth Sessions
components:
  schemas:
    APIError:
      additionalProperties: false
      description: The error object returned by the API on failure.
      properties:
        code:
          description: The specific code for the type of error returned. See the [API error codes reference](#api-error-codes) for the full set of values.
          type: integer
        error:
          description: A description of the problem that was encountered.
          type: string
        payload:
          description: Additional error details, if any. The structure varies by error type.
          type:
          - object
          - 'null'
      required:
      - code
      - error
      type: object
    OAuthSession:
      additionalProperties: false
      description: OAuthSession represents an OAuth session for a given user associated to an OAuth integration.
      properties:
        id:
          description: The internal numeric identifier of this OAuth session.
          example: '123'
          type: string
        guid:
          description: 'The unique identifier of this OAuth session which is used in REST API

            requests.'
          example: 25438b83-ea6d-4839-ae8e-53c52ac5f9ce
          format: uuid
          type: string
        user_guid:
          description: 'The unique identifier of the user that is associated with this OAuth

            session.'
          example: 21caced7-979e-4e83-ad11-01837528d9d9
          format: uuid
          type:
          - string
          - 'null'
        oauth_integration_guid:
          description: 'The unique identifier of the OAuth integration that is associated with this

            OAuth session.'
          example: dd4a5e2-4714-401a-9404-4ca8eddcef2d
          format: uuid
          type: string
        has_refresh_token:
          description: Indicates whether this OAuth session has a refresh token.
          type: boolean
        created_time:
          description: The timestamp (RFC3339) indicating when this OAuth session was created.
          example: '2020-01-02T15:04:05-07:00'
          format: date-time
          type: string
        updated_time:
          description: The timestamp (RFC3339) indicating when this OAuth session was last updated.
          example: '2020-01-02T15:04:05-07:00'
          format: date-time
          type: string
      type: object
  securitySchemes:
    apiKey:
      description: 'Prefix your API key with `Key `, e.g. `Key ABC123`.

        '
      in: header
      name: Authorization
      type: apiKey
